version: '3.8'

services:
  app_go:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_go
    command: ["/app/server"]
    environment:
      - PORT=8080
      - PYTHON_SERVICE_URL=http://app_py:8000
    ports:
      - "8080:8080"
    depends_on:
      - app_py

  app_py:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_py
    command: ["bash", "-lc", "uvicorn main:app --host 0.0.0.0 --port 8000"]
    environment:
      - PORT=8000
    ports:
      - "8001:8000"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "19090:9090"
    depends_on:
      - app_go
      - app_py

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  grafana_data:
