global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'app_go'
    static_configs:
      - targets: ['app_go:8080']

  - job_name: 'app_py'
    static_configs:
      - targets: ['app_py:8000']
